### PR TITLE
plcID: stop waiting for more MMEs when result was received

### PR DESCRIPTION
**Pull request by dvlemplgk**
ReadKey1/ReadKey2 waits unconditionally for more CNF MMEs after one
was received. Do not wait if a single device is queried because there
won't be more.

### CODE REVIEW

**Comment by dvlemplgk** [comment]
Is there any problem with merging this fix?

**Comment by mhei** [comment]
It would be nice if you could add a short source code comment before the memcmp stuff ... I had to think twice about the conditions with memcmp and && operator...

**Comment by dvlemplgk** [comment]
Added a comment to the quirky if condition.

**Comment by mhei** [comment]
Thank you, I appreciate it.

**Pull request merged**
