### PR TITLE
Psin qca7000

### PR DESCRIPTION
**Pull request by ch-aurich**
psin did not work for QCA7000 so far. This branch tries to fix that. I have no hardware here to try it out at the moment... maybe someone can have a look around and point me to possible issues. I will test it next week when I am in my office again.
At least it would be great if someone can verify that it still works works for the other chips like before ;)

Christian

### CODE REVIEW

**Comment by razzlefratz** [comment]
This is a dangerous change because the QCA7000 pre-scalars occupy a different location and have different size than other chipsets. The size difference results from using one pre-scalar for every four carriers. The psin, psout and psgraph tools really should be removed because the data format has changed with every chipset generation since the 6400.  I will leave this open we can either solve the problem or agree to remove the tools.

**Comment by ch-aurich** [comment]
For some of our customers (using the QCA7000 but not having NDA with QCA) this is one of the most usefull feature. They need to modify the prescalers and enable SLAC. They usually want to do it $SOMEHOW - it does not really matter how.

If I understand it correctly the tools are working correctly but you doubt that it is always used in a way that guarantees that results in a correct PIB file. Is this correct? If this is the only problem we could add a parameter where the user must specify which chip(-set) he uses.

**Comment by razzlefratz** [comment]
Hi Christian,

The SLAC tools, PEV and EVSE, are valid because the SLAC protocol has not
changed, to my knowledge. Since SLAC is only implemented in the QCA7000,
the PIB settings should not have changed.

The format and location of the pre-scalers has changed with each new
chipset in an effort to conserve memory and support the increase the number
of carriers. Starting with the QCA6410, QCA7000 and AR7420 chipsets,
everything changed forcing us to write the plc* series of tools. By
everything, I mean PIB structure, flash memory layout and firmware upgrade
procedure. The pre-scaler tools (ps*) have not been upgraded to match for
two reasons. The most important reason is that the location of the
pre-scaler set within the PIB is no longer fixed and may change from one
major firmware release to another. The firmware teams does not see this as
a problem because they claim that folks should not tamper with pre-scalers.
All this may take time to resolve.

Regarding your suggestion, most of the tools detect either the PLC device
type or PIB version. Some do not. My solution is to keep programs as simple
as possible by creating a new version to each tool for each chipset
generation. That way we do not break earlier programs. I tried one
implementation where programs support multiple chipset, firmware and PIB
versions and it quickly got ugly. There were (and still are) corner cases
that make those tools unusable over the network. That implementation was
release to one customer for production purposes only.

The amp* tools are for the AR7400 and QCA7450 and are mature.  The plc*
tools are for the QCA6410, QCA7000 and AR7420 but those chipsets introduced
relocatable PIB parameters and the pre-scaler formats on the QCA7000 are
different than the QCA6410 and QR7420 so the ps* tools do not work on these
chipsets.

I hope this answers your question,

**Comment by razzlefratz** [comment]
PS. I will be cherry-picking through your pull requests. You have some
great stuff in there.

**Comment by ch-aurich** [comment]
Thank you for rhe explanations Charlie. I understand what you mean. Still I believe that we need a way to modify prescalers as this is needed to adjust the output power in order to get a psd of -75 dBm/Hz as specified in ISO 15118. How should customers do this if they do not have an NDA with QCA?

**Comment by razzlefratz** [comment]
Does each customer have to apply different adjustments ? Would one set of
pre-scalers do?

**Comment by ch-aurich** [comment]
At the moment they are not doing it because we do not have a stable way to do so. This is kind of odd since ISO15118-3 has hard requirements of -73dBm/Hz to -77 dBm/Hz at the charging port. In fact this should be met for each carrier - not only as average over the whole spectrum.

Our product is a hardware module that is only one part of the charger. Hence we do not know how high the attenuation between our device and the charging port is. Therefore we can only make assumptions about how much of the signal gets lost on the way between our connector and the charging port.

Our goal is to prepare tools for our costumers so that they can measure and adjust the PSD to be compliant to ISO15118-3.

**Comment by razzlefratz** [comment]
It sounds like the immediate use case is the QCA7000. That is a static
problem that we can solve with a single program. The general case is out of
scope. Am I right?

On Thu, Apr 23, 2015 at 10:51 AM, Christian Aurich <notifications@github.com

**Comment by ch-aurich** [comment]
Yes, we do just need some tool to adpot the prescalers for the QCA7000, I do not see any immediate need for a general purpose tool.

**Comment by ch-aurich** [comment]
over the last years we tested it and recommended the use of this tool to customers - since no problems in the usage were discovered and now one except @razzlefratz has commented here I assume merging this should be fine.
@lategoodbye will fix the conflicts that arose in the meantime and then I will merge this.

So this is the last chance to express your opposition to the above actions.

**Comment by lategoodbye** [comment]
The fixed version is available here: #115

**Pull request merged**
